#!/usr/bin/env bash
rm /etc/nginx/sites-enabled/default
# Create symbolic link to the deafult file in sites-available
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default;
# Restart Nginx
service nginx restart
