#!/usr/bin/env bash
rm /etc/nginx/sites-enabled/default;
# Create symbolic link to the deafult file in sites-available
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default;
# allow port 80 in fire wall
sudo ufw allow 'Nginx HTTP'
# Restart Nginx
service nginx restart
